/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/Footer/AppFooter.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    HeaderMenu: typeof import('./components/Header/HeaderMenu.vue')['default']
    HelloWorld: typeof import('./components/Main.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    RickAndMorty: typeof import('./components/RickAndMorty/RickAndMorty.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
